In [1]:
import numpy as np

print(np.__version__)

#np.<TAB>
#np?

1.14.2


Creating Arrays from Python Lists

In [11]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [10]:
#NumPy is constrained to arrays that all contain the same type. 

np.array([1, 4, 2, 5, 3,'d']) #everything is a string 	Unicode string

array(['1', '4', '2', '5', '3', 'd'], dtype='<U21')

In [13]:
#floaot
np.array([1, 4, 2, 5.5, 3])

array([1. , 4. , 2. , 5.5, 3.5])

In [16]:
# nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])
#[range(i, i + 3) for i in [2, 4, 6]] --> list comprehension

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Creating Arrays from Scratch

In [17]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int) #the dtype integer specifies the data type

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
#create a definite array
np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#create a definite array of size 5 by 2 filled with numbers from 10



In [18]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#Create a 2 by 3 array filled with zeros


In [19]:
# Create a 3x5 array filled with 7
np.full((3, 5), 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [20]:
#a linear sequence -- remember range()
#Numpy has arange
#np.arange(start,end,step)

#one to nine
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Create a numpy array filled with even numbers from two to twenty two


| Purpose | Command |
|---------------------------------|-------------------|
| Random values | np.random.random |
| Normally distributed values | np.random.normal |
| Random integers | np.random.randint |
| Identity Matrix | np.eye |
| Uninitialized array of integers | np.empty |

The Basics of NumPy Arrays

NB : While the types of operations shown here may seem a bit dry and **pedantic**, they comprise the building blocks needed to properly analyze numerical data. Get to know them well!!

> Practise Practise Practise.... (I'll give you challenges to help you do that)
<img src="https://www.jing.fm/clipimg/detail/156-1562950_solve-challenges-improve-your-coding-skills-with-practice.png" style="width : 60%;">

| Section | Items |
|---------------------------------|--------------------------------------------------------------|
| Attributes of arrays | Determining the Size, Shape & Data Types |
| Indexing of arrays | Getting and setting the value of individual array elements |
| Slicing of arrays | Getting and setting smaller sub-arrays within a larger array |
| Reshaping of arrays | Changing the shape of a given array |
| Joining and splitting of arrays | Combining and splitting accordingly |

NumPy’s random number generator, which we will **seed** with a set value in order to
ensure that the same random arrays are generated each time this code is run:

In [26]:
np.random.seed(0) #ensure the same random numbers are generated every time

In [27]:
a1 = np.random.randint(10, size=6) # One-dimensional array
a2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
a3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [29]:
print("a3 ndim: ", a3.ndim) # number of dimensions
print("a3 shape:", a3.shape) #size of each dimension
print("a3 size: ", a3.size) #total size of the array

a3 ndim:  3
a3 shape: (3, 4, 5)
a3 size:  60


In [ ]:
#get the dimension,shape and size for a1 and a2



Array Indexing: Accessing Single Elements

>  In a one-dimensional array, you can access the ith value (counting from
zero or zero-indexed) by specifying the desired index in square brackets, just as with Python lists:

In [30]:
a1

array([5, 0, 3, 3, 7, 9])

In [ ]:
#access 7 (2 ways)



In [ ]:
#access 5 (2 ways)



In a multidimensional array, you access items using a comma-separated tuple of
indices:

In [32]:
a2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [34]:
#accessing 2
a2[0,2]

2

In [ ]:
#access 6


In [ ]:
#access 4


NumPy arrays have a fixed type. If you try to insert other types it will either raise an error or truncate

In [37]:
a1[0] = 'twe'
a1

ValueError: invalid literal for int() with base 10: 'twe'

In [39]:
a1[0] = 3.444444
a1

array([3, 0, 3, 3, 7, 9])

Array Slicing: Accessing Subarrays

> Just as we can use square brackets to access individual array elements, we can also use
them to access subarrays with the slice notation, marked by the colon (:) character.

> a[start:stop:step]

In [40]:
a1

array([3, 0, 3, 3, 7, 9])

In [53]:
a1[:2] #first two elements

array([3, 0])

In [54]:
a1[4:] #elements after index 4 -- notice that the element at the fourth index is included

array([7, 9])

In [56]:
#elements from third to fifth elements NB : start(included) : stop(not included)

#In other words
#The slice extends from the ‘start’ index and ends one item before the ‘stop’ index.
a1[3:5] #[third,fourth]

array([3, 7])

> Multidimensional slices work in the same way, with multiple slices separated by commas. 

> This is most useful in data science when specifying input variables and output variables, or splitting training rows from testing rows.

In [57]:
a2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [58]:
#a2[rowIndex,columnIndex]

# Syntax for index still remains [start:stop:step]

a2[1:2,:] #first row and all columns

array([[7, 6, 8, 8]])

In [60]:
a2[0:2,1:3] #first and second row and the second and third columns

array([[5, 2],
       [6, 8]])

In [62]:
#select the last column with all rows
a2[:,-1:]
a2[:,-1] #equivalent (combination of slicing and indexing)

array([[4],
       [8],
       [7]])

In [68]:
#select all columns(except the last) and all rows
a2[:,0:-1]

array([[3, 5, 2],
       [7, 6, 8],
       [1, 6, 7]])

In [65]:
#all even rows and columns
a2[::2,::2]


array([[3, 2],
       [1, 7]])

In [66]:
#select 
np.array([[6,8],[6,7]])



array([[6, 8],
       [6, 7]])

NB : All the slices created are still part of the larger array, modifying them changes the parent array.

> This default behavior is actually quite useful: it means that when we work with large
datasets, we can access and process pieces of these datasets without the need to copy
the underlying data buffer

- Incase you would like to create a copy, then use the copy() method


In [ ]:
#copy example
even_r_c = a2[::2,::2].copy()

Reshaping of Arrays

> Using the reshape() method

In [72]:
a4 = np.arange(1,21)
a4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [74]:
a4.reshape(5,4) #2 dimensions

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [76]:
a4.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

> Note that for this to work, the size of the initial array must match the size of the
reshaped array

In [77]:
a4.reshape(3,4)

ValueError: cannot reshape array of size 20 into shape (3,4)

In [ ]:
#create a 2d array of size 30 and reshape it into a 3d array




Array Concatenation and Splitting

> Concatenation, or joining of two arrays in NumPy, is primarily accomplished
through the routines/function/method np.concatenate, np.vstack, and np.hstack. np.concatenate
takes a tuple or list of arrays as its first argument, as we can see here:

In [81]:
d = np.array([1, 2, 3])
c = np.array([4, 5, 6])
e = np.array([7,8,9,10])
np.concatenate([d,c])

array([1, 2, 3, 4, 5, 6])

In [83]:
#you can concatenate more than two at once
np.concatenate([d,c,e])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
#np.concatenate can also be used for two-dimensional arrays:
f = np.array([[11,12,13],[14,15,16]])
g = np.array([[17,18,19],[20,21,22]])
#on first axis
np.concatenate([f,g],axis=0) #axis specifies where to concatenate, zero-indexed

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22]])

In [89]:
#on second axis
np.concatenate([f,g],axis=1) #axis specifies where to concatenate, zero-indexed

array([[11, 12, 13, 17, 18, 19],
       [14, 15, 16, 20, 21, 22]])

> Mixed dimensions you used np.vstack (vertical stack)

In [112]:
h = np.arange(0,3) # must have the same dimension except for the concatenation axis

np.vstack([f,h])

array([[11, 12, 13],
       [14, 15, 16],
       [ 0,  1,  2]])

In [110]:
i = np.array([[23,24], [25 ,26]]) #note must have the same dimensions
np.hstack([f,i])


array([[11, 12, 13, 23, 24],
       [14, 15, 16, 25, 26]])

> Splitting of arrays (Reading assignment :>)

Numpy Operations

>NB : For many types of operations, NumPy provides a convenient interface into just this
kind of statically typed, compiled routine. This is known as a **vectorized operation(Vectorization describes the absence of any explicit looping, indexing, etc., in the code - these things are taking place, of course, just “behind the scenes” in optimized, pre-compiled C code.)**
You can accomplish this by simply performing an operation on the array, which will
then be applied to each element. This vectorized approach is designed to push the
loop into the compiled layer that underlies NumPy, leading to much faster execution


- Arithmetic Operators Implemented in Numpy

<img src="ufuncs.png">

- Aggregation functions available in NumPy
<img src="aggregation_functions.png">

Loading data files

In [27]:
# Kenya Police workforce - first_column(year),second_column(Male),Third column(Female)
data = np.genfromtxt('ke_police_workforce.csv', delimiter=',',usecols=[0,1,2])
data

OSError: ke_police_workforce.csv not found.

In [131]:
#Total male officers?
#remmeber slicing?
female_officers = data[:,1].copy()
#remove first item
np.sum(female_officers[1:])

183826.0

# Exercises 

1. Create a null array of size 12 but the sixth value which is 1

In [2]:
import numpy as np
a=np.empty([12],dtype=int)
a[5]=1
print(a)

[0 0 0 0 0 1 0 0 0 0 0 0]


2. Create a vector with values ranging from 22 to 59

In [6]:
import numpy as np
v=np.arange(22,59)
print(v)

[22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45
 46 47 48 49 50 51 52 53 54 55 56 57 58]


3. Reverse a vector (first element becomes last)

In [8]:
import numpy as np
v=np.arange(22,59)
v=v[::-1]
print(v)

[58 57 56 55 54 53 52 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35
 34 33 32 31 30 29 28 27 26 25 24 23 22]


 4. Create a 3x3 matrix with values ranging from 0 to 26

In [12]:
import numpy as np
matrix=np.arange(0,26).reshape(3,3)

print(matrix)

ValueError: cannot reshape array of size 26 into shape (3,3)

5. Create a 7x7 array with random values and find the minimum and maximum values

In [25]:
import numpy as np
a=np.random.randint(50,size=(7,7))


max_value=np.nanmax(a)
min_value=np.nanmin(a)

print(a)
print(max_value)
print(min_value)

[[38  8 38  1 34 14 49]
 [ 2 16 21  2 33 26 30]
 [47 24  8 17  8 21  5]
 [25 49 10 39 35 26 15]
 [33 15 11 45 25 38 23]
 [40 15 38  6  7 46 14]
 [ 4 10 27  8 34  3 24]]
49
1


6. Create a random vector of size 76 and find the mean value

In [27]:
import numpy as np
x=np.random.randint(76,size=(4,19))
mean=np.nanmean(x)

print(x)
print(mean)


[[10 27 70 67 41 68 50 72 48 65 73 75 37 48  8 36 26 61 15]
 [ 9 61 56 40 19 67 73 46 60 22 69 47 58  6 40 65  1  2 35]
 [74 12 22 65 17 75 70 61 11 48 42 74 75 45  7 39 47 59 59]
 [51 66 74  6 47 33 18 69 44 33 65 32 28  4 48 58 62 75 42]]
45.13157894736842


7.  Create a 2d array with one's on the border and zero's inside

In [ ]:
import numpy as np


8. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
1,6,4

9. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [3]:
import numpy as np
a=np.random.randint(15,size=(5,3))
b=np.random.randint(6,size=(3,2))

prod=a.dot(b)

print(prod)

[[ 65  56]
 [ 73  62]
 [ 99  88]
 [ 68  61]
 [118 108]]


10. How to get all the dates corresponding to the month of February 2019?

In [15]:
import numpy as np
np.arange('2020-02','2020-03',dtype='datetime64[D]')


array(['2020-02-01', '2020-02-02', '2020-02-03', '2020-02-04',
       '2020-02-05', '2020-02-06', '2020-02-07', '2020-02-08',
       '2020-02-09', '2020-02-10', '2020-02-11', '2020-02-12',
       '2020-02-13', '2020-02-14', '2020-02-15', '2020-02-16',
       '2020-02-17', '2020-02-18', '2020-02-19', '2020-02-20',
       '2020-02-21', '2020-02-22', '2020-02-23', '2020-02-24',
       '2020-02-25', '2020-02-26', '2020-02-27', '2020-02-28',
       '2020-02-29'], dtype='datetime64[D]')

11. Create a random vector of size 10 and sort it

In [5]:
a=np.random.randint(10, size=(2,5))
print(a)
np.sort(a,axis=None)

[[2 6 4 7 5]
 [1 5 6 2 7]]


array([1, 2, 2, 4, 5, 5, 6, 6, 7, 7])

12. Consider two random array Z and J, check if they are equal

In [8]:
d=np.random.randint(4,size=(2,2))
e=np.random.randint(6,size=(2,3))
np.array_equal(d,e)


False

13. How would you read the following file?


```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

14. Consider the csv file [data.csv](https://docs.google.com/spreadsheets/d/1sQ-I_f1XdaCFdYmMbPF3tCPtLeavzYz_79L2UfWDQD8/export?format=csv&id=1sQ-I_f1XdaCFdYmMbPF3tCPtLeavzYz_79L2UfWDQD8&gid=94934202)

[Click here to download the file](https://docs.google.com/spreadsheets/d/1sQ-I_f1XdaCFdYmMbPF3tCPtLeavzYz_79L2UfWDQD8/export?format=csv&id=1sQ-I_f1XdaCFdYmMbPF3tCPtLeavzYz_79L2UfWDQD8&gid=94934202)

Required : Load the file using Numpy and answer the following Questions

14. a) What is the total male population?
14. b) What is the total female population?
14. c) What is the total population?
14. d) What is the percentage of male vs female population?
14. e) Which age-group has the highest population?
14. f) Which age group has the highest female population?

In [26]:
from numpy import genfromtxt
data = np.genfromtxt('C:\\Users\Merab\Desktop\population_data.csv', delimiter=',',usecols=[0,1,2,3])
data

array([[     nan,      nan,      nan,      nan],
       [     nan, 2938867., 3000439., 5939306.],
       [     nan, 2045890., 2123653., 4169543.],
       [     nan, 2020998., 1754105., 3775103.],
       [     nan, 1672110., 1529116., 3201226.],
       [     nan, 1262471., 1257035., 2519506.],
       [     nan, 1004271., 1004361., 2008632.],
       [     nan,  732575.,  743594., 1476169.],
       [     nan,  637469.,  635276., 1272745.],
       [     nan,  477860.,  478346.,  956206.],
       [     nan,  352487.,  359466.,  711953.],
       [     nan,  298581.,  295197.,  593778.],
       [     nan,  207612.,  183151.,  390763.],
       [     nan,  179000.,  160301.,  339301.],
       [     nan,  118675.,   99833.,  218508.],
       [     nan,  224576.,  159125.,  383701.]])

In [ ]:
#14a
females = data[:,1].copy()
np.sum(females)
